# Generated by Django 5.1.1 on 2025-02-28 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_week_start_date', models.DateField(help_text='设置学期第一周的开始日期（周一）', verbose_name='第一周起始日期')),
                ('semester_name', models.CharField(default='2025年春季学期', max_length=50, verbose_name='学期名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='节目名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('day_of_week', models.IntegerField(choices=[(1, '周一'), (2, '周二'), (4, '周四')], verbose_name='播出星期')),
                ('icon_class', models.CharField(default='fa-newspaper', max_length=50, verbose_name='图标类名')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='主题颜色')),
                ('is_biweekly', models.BooleanField(default=False, verbose_name='是否双周轮播')),
                ('alternate_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_program', to='broadcast.programcategory', verbose_name='轮替节目')),
            ],
            options={
                'verbose_name': '节目类别',
                'verbose_name_plural': '节目类别',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('publish_date', models.DateField(verbose_name='发布日期')),
                ('link', models.URLField(verbose_name='节目链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前活跃')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='broadcast.programcategory', verbose_name='节目类别')),
            ],
            options={
                'verbose_name': '节目',
                'verbose_name_plural': '节目',
                'ordering': ['-publish_date'],
            },
        ),
    ]
